@tool
extends RefCounted

const ENDPOINTS := [
	"/health",
	"/project/info",
	"/editor/state",
	"/scene/tree",
	"/scene/nodes/find",
	"/scene/tabs",
	"/selection",
	"/logs",
	"/editor/screenshot",
	"/node-types/search",
	"/filesystem/state",
	"/filesystem/list",
	"/filesystem/file/read",
	"/project/settings",
	"/input/map",
	"/script/read",
	"/script/search",
	"/script/validate",
	"/script/symbols",
	"/script/editor/state",
	"/script/cursor/state",
	"/import/assets",
	"/import/metadata",
	"/import/diagnostics",
	"/import/events",
	"/run/settings",
	"/run/status",
	"/export/presets",
	"/debugger/state",
	"/runtime/state",
	"/runtime/events",
	"/runtime/node/properties",
	"/runtime/node/property/set/result",
	"/runtime/node/method/call/result",
	"/runtime/input/send/result",
	"/runtime/state/result",
	"/runtime/screenshot/result",
	"/viewport/screenshot",
	"/viewport/state",
	"/animation/list",
	"/animation/state",
	"/audio/buses",
	"/localization/state"
]

const ROUTES := {
	"/health": { "handler": "_health" },
	"/project/info": { "handler": "_project_info" },
	"/editor/state": { "handler": "_editor_state" },
	"/scene/tree": { "handler": "_scene_tree", "arg": "query" },
	"/scene/nodes/find": { "handler": "_find_nodes", "arg": "query" },
	"/scene/tabs": { "handler": "_open_scene_tabs" },
	"/selection": { "handler": "_selection" },
	"/logs": { "handler": "_logs_response" },
	"/editor/screenshot": { "handler": "_capture_editor_screenshot" },
	"/node-types/search": { "handler": "_search_node_types", "arg": "query" },
	"/filesystem/state": { "handler": "_filesystem_state" },
	"/filesystem/list": { "handler": "_list_filesystem", "arg": "query" },
	"/filesystem/file/read": { "handler": "_read_text_file", "arg": "query" },
	"/project/settings": { "handler": "_project_settings", "arg": "query" },
	"/input/map": { "handler": "_input_map" },
	"/script/read": { "handler": "_read_script", "arg": "query" },
	"/script/search": { "handler": "_search_in_scripts", "arg": "query" },
	"/script/validate": { "handler": "_validate_script", "arg": "query" },
	"/script/symbols": { "handler": "_script_symbols", "arg": "query" },
	"/script/editor/state": { "handler": "_script_editor_state" },
	"/script/cursor/state": { "handler": "_script_cursor_state" },
	"/import/assets": { "handler": "_list_imported_assets", "arg": "query" },
	"/import/metadata": { "handler": "_get_import_metadata", "arg": "query" },
	"/import/diagnostics": { "handler": "_get_import_diagnostics", "arg": "query" },
	"/import/events": { "handler": "_import_events_response", "arg": "query" },
	"/run/settings": { "handler": "_run_settings" },
	"/run/status": { "handler": "_run_status" },
	"/export/presets": { "handler": "_export_presets" },
	"/debugger/state": { "handler": "_debugger_state" },
	"/runtime/state": { "handler": "_runtime_state", "arg": "query" },
	"/runtime/events": { "handler": "_runtime_events", "arg": "query" },
	"/runtime/node/properties": { "handler": "_runtime_node_properties", "arg": "query" },
	"/runtime/node/property/set/result": { "handler": "_runtime_node_property_set_result", "arg": "query" },
	"/runtime/node/method/call/result": { "handler": "_runtime_node_method_call_result", "arg": "query" },
	"/runtime/input/send/result": { "handler": "_runtime_input_send_result", "arg": "query" },
	"/runtime/state/result": { "handler": "_runtime_state_result", "arg": "query" },
	"/runtime/screenshot/result": { "handler": "_runtime_screenshot_result", "arg": "query" },
	"/viewport/screenshot": { "handler": "_capture_viewport_screenshot", "arg": "query" },
	"/viewport/state": { "handler": "_viewport_state", "arg": "query" },
	"/animation/list": { "handler": "_list_animations", "arg": "query" },
	"/animation/state": { "handler": "_get_animation_state", "arg": "query" },
	"/audio/buses": { "handler": "_list_audio_buses", "arg": "query" },
	"/localization/state": { "handler": "_get_localization_state", "arg": "query" }
}
