@tool
extends RefCounted

const ROUTES := {
	"/filesystem/folder/create": { "handler": "_create_folder", "arg": "body", "methodError": "folder creation requires POST" },
	"/filesystem/file/write": { "handler": "_write_text_file", "arg": "body", "methodError": "file write requires POST" },
	"/filesystem/file/write-binary": { "handler": "_write_binary_file", "arg": "body", "methodError": "binary file write requires POST" },
	"/filesystem/move": { "handler": "_move_filesystem_entry", "arg": "body", "methodError": "filesystem move requires POST" },
	"/filesystem/copy": { "handler": "_copy_filesystem_entry", "arg": "body", "methodError": "filesystem copy requires POST" },
	"/filesystem/batch": { "handler": "_batch_filesystem_operations", "arg": "body", "methodError": "filesystem batch requires POST" },
	"/filesystem/delete": { "handler": "_delete_filesystem_entry", "arg": "body", "methodError": "filesystem delete requires POST" },
	"/resource/open": { "handler": "_open_resource", "arg": "body", "methodError": "resource open requires POST" },
	"/resource/focus": { "handler": "_focus_resource", "arg": "body", "methodError": "resource focus requires POST" },
	"/resource/create": { "handler": "_create_resource", "arg": "body", "methodError": "resource creation requires POST" },
	"/resource/save": { "handler": "_save_resource", "arg": "body", "methodError": "resource save requires POST" },
	"/resource/sprite-frames/create": { "handler": "_create_sprite_frames_resource", "arg": "body", "methodError": "SpriteFrames creation requires POST" },
	"/resource/tile-set/create": { "handler": "_create_tile_set_resource", "arg": "body", "methodError": "TileSet creation requires POST" },
	"/resource/shader-material/create": { "handler": "_create_shader_material_resource", "arg": "body", "methodError": "ShaderMaterial creation requires POST" },
	"/project/setting/set": { "handler": "_set_project_setting", "arg": "body", "methodError": "project setting update requires POST" },
	"/project/setting/metadata/set": { "handler": "_set_project_setting_metadata", "arg": "body", "methodError": "project setting metadata update requires POST" },
	"/input/action/set": { "handler": "_set_input_action", "arg": "body", "methodError": "input action update requires POST" },
	"/script/write": { "handler": "_write_script", "arg": "body", "methodError": "script write requires POST" },
	"/script/edit": { "handler": "_edit_script", "arg": "body", "methodError": "script edit requires POST" },
	"/script/open": { "handler": "_open_script", "arg": "body", "methodError": "script open requires POST" },
	"/script/goto-line": { "handler": "_goto_script_line", "arg": "body", "methodError": "script goto line requires POST" },
	"/script/refactor/replace": { "handler": "_replace_in_scripts", "arg": "body", "methodError": "script replace requires POST" },
	"/script/create": { "handler": "_create_script", "arg": "body", "methodError": "script creation requires POST" },
	"/script/attach": { "handler": "_attach_script", "arg": "body", "methodError": "script attachment requires POST" },
	"/import/options/set": { "handler": "_set_import_options", "arg": "body", "methodError": "import option update requires POST" },
	"/import/reimport": { "handler": "_reimport_assets", "arg": "body", "methodError": "asset reimport requires POST" },
	"/export/preset/upsert": { "handler": "_upsert_export_preset", "arg": "body", "methodError": "export preset upsert requires POST" },
	"/debugger/breakpoint/set": { "handler": "_set_debugger_breakpoint", "arg": "body", "methodError": "debugger breakpoint update requires POST" },
	"/debugger/profiler/toggle": { "handler": "_toggle_debugger_profiler", "arg": "body", "methodError": "debugger profiler toggle requires POST" },
	"/debugger/message/send": { "handler": "_send_debugger_message", "arg": "body", "methodError": "debugger message send requires POST" },
	"/runtime/probe/install": { "handler": "_install_runtime_probe", "arg": "body", "methodError": "runtime probe install requires POST" },
	"/runtime/node/property/set": { "handler": "_set_runtime_node_property", "arg": "body", "methodError": "runtime node property set requires POST" },
	"/runtime/node/method/call": { "handler": "_call_runtime_node_method", "arg": "body", "methodError": "runtime node method call requires POST" },
	"/runtime/input/send": { "handler": "_send_runtime_input", "arg": "body", "methodError": "runtime input send requires POST" },
	"/runtime/screenshot": { "handler": "_capture_runtime_screenshot", "arg": "body", "methodError": "runtime screenshot requires POST" },
	"/editor/main-screen/set": { "handler": "_set_editor_main_screen", "arg": "body", "methodError": "editor main screen switch requires POST" },
	"/editor/action/invoke": { "handler": "_invoke_editor_action", "arg": "body", "methodError": "editor action invoke requires POST" },
	"/viewport/camera/set": { "handler": "_set_viewport_camera", "arg": "body", "methodError": "viewport camera update requires POST" },
	"/viewport/input/send": { "handler": "_send_viewport_input", "arg": "body", "methodError": "viewport input send requires POST" },
	"/selection/set": { "handler": "_set_selection", "arg": "body", "methodError": "selection update requires POST" },
	"/selection/focus/node": { "handler": "_focus_node", "arg": "body", "methodError": "node focus requires POST" },
	"/run/main-scene/set": { "handler": "_set_main_scene", "arg": "body", "methodError": "main scene update requires POST" },
	"/run/main": { "handler": "_run_main_scene", "arg": "body", "methodError": "run main scene requires POST" },
	"/run/current": { "handler": "_run_current_scene", "arg": "body", "methodError": "run current scene requires POST" },
	"/run/custom": { "handler": "_run_custom_scene", "arg": "body", "methodError": "run custom scene requires POST" },
	"/run/stop": { "handler": "_stop_running_scene", "methodError": "stop running scene requires POST" },
	"/run/reload": { "handler": "_reload_running_scene", "arg": "body", "methodError": "reload running scene requires POST" },
	"/scene/open": { "handler": "_open_scene", "arg": "body", "methodError": "scene open requires POST" },
	"/scene/create": { "handler": "_create_scene", "arg": "body", "methodError": "scene creation requires POST" },
	"/scene/node/create": { "handler": "_create_node", "arg": "body", "methodError": "node creation requires POST" },
	"/scene/node/create-with-script": { "handler": "_create_node_with_script", "arg": "body", "methodError": "node creation with script requires POST" },
	"/scene/node/rename": { "handler": "_rename_node", "arg": "body", "methodError": "node rename requires POST" },
	"/scene/node/delete": { "handler": "_delete_node", "arg": "body", "methodError": "node delete requires POST" },
	"/scene/node/duplicate": { "handler": "_duplicate_node", "arg": "body", "methodError": "node duplicate requires POST" },
	"/scene/node/reparent": { "handler": "_reparent_node", "arg": "body", "methodError": "node reparent requires POST" },
	"/scene/node/reorder": { "handler": "_reorder_node", "arg": "body", "methodError": "node reorder requires POST" },
	"/scene/tile-map-layer/cells/set": { "handler": "_set_tile_map_layer_cells", "arg": "body", "methodError": "TileMapLayer cell update requires POST" },
	"/scene/tile-map-layer/terrain/paint": { "handler": "_paint_tile_map_layer_terrain", "arg": "body", "methodError": "TileMapLayer terrain paint requires POST" },
	"/node/material/assign": { "handler": "_assign_material", "arg": "body", "methodError": "material assignment requires POST" },
	"/inspector/properties": { "handler": "_inspector_properties", "arg": "query", "method": "" },
	"/inspector/property/set": { "handler": "_set_node_property", "arg": "body", "methodError": "property set requires POST" },
	"/scene/save-as": { "handler": "_save_scene_as", "arg": "body", "methodError": "scene save-as requires POST" },
	"/scene/save": { "handler": "_save_current_scene", "arg": "body", "methodError": "scene save requires POST" },
	"/scene/switch": { "handler": "_switch_scene_tab", "arg": "body", "methodError": "scene switch requires POST" },
	"/scene/close": { "handler": "_close_scene_tab", "arg": "body", "methodError": "scene close requires POST" },
	"/scene/mark-unsaved": { "handler": "_mark_scene_unsaved", "arg": "body", "methodError": "scene mark-unsaved requires POST" },
	"/editor/undo": { "handler": "_undo_editor_action", "arg": "body", "methodError": "editor undo requires POST" },
	"/editor/redo": { "handler": "_redo_editor_action", "arg": "body", "methodError": "editor redo requires POST" },
	"/animation/upsert": { "handler": "_upsert_animation", "arg": "body", "methodError": "animation upsert requires POST" },
	"/animation/play": { "handler": "_play_animation", "arg": "body", "methodError": "animation playback requires POST" },
	"/animation/stop": { "handler": "_stop_animation", "arg": "body", "methodError": "animation stop requires POST" },
	"/animation/scene/instance": { "handler": "_instance_animated_scene", "arg": "body", "methodError": "animated scene instance requires POST" },
	"/animation/tree/state-machine": { "handler": "_create_animation_tree_state_machine", "arg": "body", "methodError": "animation tree state machine requires POST" },
	"/animation/tree/travel": { "handler": "_travel_animation_tree", "arg": "body", "methodError": "animation tree travel requires POST" },
	"/ui/control/create": { "handler": "_create_ui_control", "arg": "body", "methodError": "UI control creation requires POST" },
	"/ui/control/layout": { "handler": "_set_control_layout", "arg": "body", "methodError": "UI control layout requires POST" },
	"/ui/theme/create": { "handler": "_create_ui_theme", "arg": "body", "methodError": "UI theme creation requires POST" },
	"/ui/theme/override": { "handler": "_apply_ui_theme_override", "arg": "body", "methodError": "UI theme override requires POST" },
	"/ui/signal/connect": { "handler": "_connect_ui_signal", "arg": "body", "methodError": "UI signal connection requires POST" },
	"/particles/create-3d": { "handler": "_create_gpu_particles_3d", "arg": "body", "methodError": "GPUParticles3D creation requires POST" },
	"/particles/create-2d": { "handler": "_create_gpu_particles_2d", "arg": "body", "methodError": "GPUParticles2D creation requires POST" },
	"/particles/material/configure": { "handler": "_configure_particle_process_material", "arg": "body", "methodError": "particle material configuration requires POST" },
	"/particles/emitting/set": { "handler": "_set_particles_emitting", "arg": "body", "methodError": "particle emission state requires POST" },
	"/navigation/region/create": { "handler": "_create_navigation_region_3d", "arg": "body", "methodError": "navigation region creation requires POST" },
	"/navigation/mesh/bake": { "handler": "_bake_navigation_mesh_3d", "arg": "body", "methodError": "navigation mesh bake requires POST" },
	"/navigation/agent/create": { "handler": "_create_navigation_agent_3d", "arg": "body", "methodError": "navigation agent creation requires POST" },
	"/navigation/script/target-follow/create": { "handler": "_create_navigation_target_follow_script", "arg": "body", "methodError": "navigation target-follow script creation requires POST" },
	"/audio/bus/upsert": { "handler": "_upsert_audio_bus", "arg": "body", "methodError": "audio bus upsert requires POST" },
	"/audio/bus/remove": { "handler": "_remove_audio_bus", "arg": "body", "methodError": "audio bus remove requires POST" },
	"/audio/bus/effect/upsert": { "handler": "_upsert_audio_bus_effect", "arg": "body", "methodError": "audio bus effect upsert requires POST" },
	"/audio/player/create": { "handler": "_create_audio_stream_player", "arg": "body", "methodError": "audio stream player creation requires POST" },
	"/localization/csv/create": { "handler": "_create_csv_translation", "arg": "body", "methodError": "CSV translation creation requires POST" },
	"/localization/file/register": { "handler": "_register_translation_file", "arg": "body", "methodError": "translation file registration requires POST" },
	"/localization/locale/set": { "handler": "_set_locale", "arg": "body", "methodError": "locale set requires POST" },
	"/multiplayer/enet-script/create": { "handler": "_create_enet_multiplayer_script", "arg": "body", "methodError": "ENet multiplayer script creation requires POST" },
	"/multiplayer/spawner/create": { "handler": "_create_multiplayer_spawner", "arg": "body", "methodError": "multiplayer spawner creation requires POST" },
	"/multiplayer/synchronizer/create": { "handler": "_create_multiplayer_synchronizer", "arg": "body", "methodError": "multiplayer synchronizer creation requires POST" },
	"/multiplayer/state-script/create": { "handler": "_create_multiplayer_state_script", "arg": "body", "methodError": "multiplayer state script creation requires POST" }
}
