import test from "node:test";
import assert from "node:assert/strict";

import { createMcpProcess } from "../helpers/server-harness.js";

test("Godot MCP server handles initialize, listing, and version tool calls", async () => {
  const server = createMcpProcess();

  try {
    const initialized = await server.request("initialize", {
      protocolVersion: "2024-11-05",
      capabilities: {},
      clientInfo: { name: "node-test", version: "0.0.0" }
    });
    assert.equal(initialized.result.serverInfo.name, "niua-godot-mcp");

    const tools = await server.request("tools/list");
    const toolNames = tools.result.tools.map((tool) => tool.name);
    assert.deepEqual(toolNames, [
      "get_godot_version",
      "create_project",
      "open_project",
      "get_open_projects",
      "close_project",
      "import_project",
      "install_project_addon",
      "list_known_projects",
      "forget_project",
      "diagnose_project_setup",
      "discover_projects",
      "discover_editor_bridges",
      "list_scenes",
      "get_editor_state",
      "get_project_info",
      "get_scene_tree",
      "get_open_scene_tabs",
      "get_selection",
      "set_selection",
      "focus_node",
      "get_output_logs",
      "get_filesystem_dock_state",
      "list_filesystem",
      "create_folder",
      "read_text_file",
      "write_text_file",
      "write_binary_file",
      "move_filesystem_entry",
      "copy_filesystem_entry",
      "batch_filesystem_operations",
      "delete_filesystem_entry",
      "open_resource",
      "focus_resource",
      "create_resource",
      "save_resource",
      "create_sprite_frames",
      "create_tile_set",
      "create_material",
      "create_shader_material",
      "get_project_settings",
      "set_project_setting",
      "set_project_setting_metadata",
      "get_input_map",
      "set_input_action",
      "read_script",
      "write_script",
      "open_script",
      "validate_script",
      "diagnose_script",
      "diagnose_project_scripts",
      "get_script_symbols",
      "get_script_editor_state",
      "get_script_cursor_state",
      "goto_script_line",
      "replace_in_scripts",
      "create_script",
      "attach_script",
      "import_project_assets",
      "list_imported_assets",
      "get_import_metadata",
      "get_import_diagnostics",
      "set_import_options",
      "reimport_assets",
      "get_import_events",
      "get_run_settings",
      "set_main_scene",
      "get_run_status",
      "run_main_scene",
      "run_current_scene",
      "run_custom_scene",
      "stop_running_scene",
      "reload_running_scene",
      "list_export_presets",
      "upsert_export_preset",
      "diagnose_export_templates",
      "validate_export_preset",
      "export_project",
      "get_debugger_state",
      "set_debugger_breakpoint",
      "toggle_debugger_profiler",
      "send_debugger_message",
      "install_runtime_probe",
      "get_runtime_state",
      "get_runtime_events",
      "get_runtime_node_properties",
      "set_runtime_node_property",
      "capture_runtime_screenshot",
      "upsert_animation",
      "list_animations",
      "play_animation",
      "stop_animation",
      "get_animation_state",
      "instance_animated_scene",
      "create_animation_tree_state_machine",
      "travel_animation_tree",
      "create_ui_control",
      "set_control_layout",
      "create_ui_theme",
      "apply_ui_theme_override",
      "connect_ui_signal",
      "create_gpu_particles_3d",
      "create_gpu_particles_2d",
      "configure_particle_process_material",
      "set_particles_emitting",
      "create_navigation_region_3d",
      "bake_navigation_mesh_3d",
      "create_navigation_agent_3d",
      "create_navigation_target_follow_script",
      "list_audio_buses",
      "upsert_audio_bus",
      "remove_audio_bus",
      "upsert_audio_bus_effect",
      "create_audio_stream_player",
      "create_csv_translation",
      "register_translation_file",
      "set_locale",
      "get_localization_state",
      "create_enet_multiplayer_script",
      "create_multiplayer_spawner",
      "create_multiplayer_synchronizer",
      "create_multiplayer_state_script",
      "capture_editor_screenshot",
      "capture_viewport_screenshot",
      "get_viewport_state",
      "set_viewport_camera",
      "send_viewport_input",
      "set_editor_main_screen",
      "invoke_editor_action",
      "open_scene",
      "create_scene",
      "save_scene_as",
      "switch_scene_tab",
      "close_scene",
      "mark_scene_unsaved",
      "undo_editor_action",
      "redo_editor_action",
      "search_node_types",
      "create_node",
      "create_sprite_2d",
      "create_animated_sprite_2d",
      "create_tile_map_layer",
      "set_tile_map_layer_cells",
      "paint_tile_map_layer_terrain",
      "create_camera_2d",
      "create_collision_shape_2d",
      "create_static_body_2d",
      "create_character_body_2d",
      "create_area_2d",
      "create_light_3d",
      "create_camera_3d",
      "create_collision_shape_3d",
      "create_mesh_instance_3d",
      "create_rigid_body_3d",
      "create_character_body_3d",
      "create_static_body_3d",
      "create_area_3d",
      "create_2d_playable_blockout",
      "create_2d_character_controller",
      "create_2d_trigger_zone",
      "create_3d_playable_blockout",
      "create_3d_character_controller",
      "create_node_with_script",
      "rename_node",
      "delete_node",
      "duplicate_node",
      "reparent_node",
      "reorder_node",
      "get_inspector_properties",
      "set_node_property",
      "assign_material",
      "save_current_scene"
    ]);

    const resources = await server.request("resources/list");
    const resourceUris = resources.result.resources.map((resource) => resource.uri);
    assert.deepEqual(resourceUris, [
      "godot://project/info",
      "godot://project/settings",
      "godot://input/map",
      "godot://editor/state",
      "godot://filesystem/tree",
      "godot://import/assets",
      "godot://import/events",
      "godot://run/settings",
      "godot://run/status",
      "godot://export/presets",
      "godot://debugger/state",
      "godot://runtime/state",
      "godot://runtime/events",
      "godot://scene/tree",
      "godot://selection",
      "godot://logs"
    ]);

    const version = await server.request("tools/call", {
      name: "get_godot_version",
      arguments: {}
    });
    assert.match(version.result.content[0].text, /4\.6\.2\.test/);
  } finally {
    await server.close();
  }
});
