export {
  CREATE_CAMERA_3D_SCHEMA,
  CREATE_LIGHT_3D_SCHEMA,
  CREATE_MESH_INSTANCE_3D_SCHEMA
} from "./schemas/visual.js";

export {
  CREATE_AREA_3D_SCHEMA,
  CREATE_CHARACTER_BODY_3D_SCHEMA,
  CREATE_COLLISION_SHAPE_3D_SCHEMA,
  CREATE_RIGID_BODY_3D_SCHEMA,
  CREATE_STATIC_BODY_3D_SCHEMA
} from "./schemas/physics.js";
