import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { GODOT_MCP_TOOLS } from "../src/godot-mcp/tools/index.js";

const JS_TYPE = { string: "string", integer: "number", number: "number", boolean: "boolean", object: "object", array: "Array" };

function escapeJsdoc(text) {
  return text.replace(/\*\//g, "* /");
}

function jsdocFor(tool) {
  const lines = [];
  const desc = escapeJsdoc((tool.description || tool.name).replace(/\s+/g, " ").trim());
  lines.push(`     * ${desc}`);
  const props = (tool.inputSchema && tool.inputSchema.properties) || {};
  const required = new Set((tool.inputSchema && tool.inputSchema.required) || []);
  lines.push("     * @param {object} [args]");
  for (const key of Object.keys(props).sort()) {
    const p = props[key] || {};
    const t = JS_TYPE[p.type] || "*";
    const pdesc = escapeJsdoc((p.description || "").replace(/\s+/g, " ").trim()).slice(0, 100);
    const name = required.has(key) ? `args.${key}` : `[args.${key}]`;
    lines.push(`     * @param {${t}} ${name}${pdesc ? " " + pdesc : ""}`);
  }
  return lines.join("\n");
}

export function renderSdk(tools) {
  const byCat = new Map();
  for (const t of tools) {
    const cat = t.category || "misc";
    if (!byCat.has(cat)) byCat.set(cat, []);
    byCat.get(cat).push(t);
  }
  const cats = [...byCat.keys()].sort((a, b) => a.localeCompare(b));
  const parts = [];
  parts.push("// AUTO-GENERATED by scripts/gen-sdk.mjs — DO NOT EDIT.");
  parts.push("// Regenerate: `node scripts/gen-sdk.mjs`. Drift is enforced by test.");
  parts.push("");
  parts.push("export function buildNamespaces(call) {");
  parts.push("  return {");
  for (const cat of cats) {
    const list = byCat.get(cat).slice().sort((a, b) => a.name.localeCompare(b.name));
    parts.push(`    ${JSON.stringify(cat)}: {`);
    for (const t of list) {
      parts.push("      /**");
      parts.push(jsdocFor(t));
      parts.push("     */");
      parts.push(`      ${JSON.stringify(t.name)}: (args = {}) => call(${JSON.stringify(t.name)}, args),`);
    }
    parts.push("    },");
  }
  parts.push("  };");
  parts.push("}");
  parts.push("");
  return parts.join("\n");
}

const isMain = fileURLToPath(import.meta.url) === path.resolve(process.argv[1] || "");
if (isMain) {
  const out = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../src/godot-mcp/sdk/generated.js");
  await writeFile(out, renderSdk(GODOT_MCP_TOOLS), "utf8");
  // eslint-disable-next-line no-console
  console.log(`wrote ${out}`);
}
