export {
  CLOSE_PROJECT_SCHEMA,
  CREATE_PROJECT_SCHEMA,
  FORGET_PROJECT_SCHEMA,
  GET_OPEN_PROJECTS_SCHEMA,
  IMPORT_PROJECT_SCHEMA,
  INSTALL_PROJECT_ADDON_SCHEMA,
  LIST_KNOWN_PROJECTS_SCHEMA,
  OPEN_PROJECT_SCHEMA
} from "./schemas/lifecycle.js";
export { DIAGNOSE_PROJECT_SETUP_SCHEMA } from "./schemas/diagnostics.js";
export {
  DISCOVER_EDITOR_BRIDGES_SCHEMA,
  DISCOVER_PROJECTS_SCHEMA,
  LIST_SCENES_SCHEMA
} from "./schemas/discovery.js";
export { OUTPUT_LOGS_SCHEMA } from "./schemas/logs.js";
